# name: devops-project-1
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: ishchts/devops-for-programmers-project-74
    command: bash -c 'sleep 10 && npm run test'
    environment:
        - DATABASE_HOST=${DATABASE_HOST-db}
        - DATABASE_NAME=${DATABASE_NAME-postgres}
        - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD-password}
        - DATABASE_PORT=${DATABASE_PORT-5432}
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
        - POSTGRES_DB=${DATABASE_NAME-postgres}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD-password}
        - POSTGRES_USER=${DATABASE_USERNAME-postgres}

volumes:
  db_data: 