services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: bash -c 'sleep 10 && npm start'
    volumes:
      - "./app:/app"
    depends_on:
      - db

  
  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


volumes:
  caddy_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: $PWD/services/caddy/caddy_data

  caddy_config:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: $PWD/services/caddy/caddy_config